### ISSUE TITLE
mpvue转码后的微信程序是否可以转支付宝?

### ISSUE THREAD

**Issue by huqiliang** [ant-move/Antmove#12]
vscode插件提示转换成功，但是没发现任何文件。

**Comment by xiaofuzi** [comment]
是按照如下命令转换的吗？https://ant-move.github.io/website/docs/readme.html#vscode-%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4 如果还有问题可进群沟通，有技术同学支持。

**Comment by huqiliang** [comment]
> 是按照如下命令转换的吗？https://ant-move.github.io/website/docs/readme.html#vscode-%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4 如果还有问题可进群沟通，有技术同学支持。

是的 Antmove: Run antmove wx-alipay ，群怎么加？麻烦发个二维码

**Comment by amap-appx** [comment]
> > 是按照如下命令转换的吗？https://ant-move.github.io/website/docs/readme.html#vscode-%E7%BC%96%E8%AF%91%E6%AD%A5%E9%AA%A4 如果还有问题可进群沟通，有技术同学支持。
> 
> 是的 Antmove: Run antmove wx-alipay ，群怎么加？麻烦发个二维码

Antmove的github readme.md最底下有二维码
