### ISSUE TITLE
自定义脚本文件的引用

### ISSUE THREAD

**Issue by wuxiaofang21** [ant-move/Antmove#14]
支付宝小程序转微信小程序，支付宝中<import-sjs name="util" from="../../utils/util.sjs"/>，转成微信后，会变成绝对路径<wxs module='util' src='/utils/util.wxs'>，必须手动修改成相对路径，如果引用的地方过多，挺麻烦的
支付宝中<import-sjs name="util" from="../../utils/util.sjs"/>
转化后的微信中<wxs module='util' src='/utils/util.wxs'>

**Comment by wuxiaofang21** [comment]
支付宝中`<import-sjs name="util" from="../../utils/util.sjs"/>`
转化后的微信中`<wxs module='util' src='/utils/util.wxs'>`

**Comment by xiaofuzi** [comment]
fixed in 1.0.3
