### ISSUE TITLE
编译后出现了页面找不到的问题

### ISSUE THREAD

**Issue by KDWangBoss** [ant-move/Antmove#17]
问题：Error: page 'pages/my/my' not found!
    at r (af-appx.worker.ide.min.js:7)
    at z.O [as newPage] (af-appx.worker.ide.min.js:7)
    at af-appx.worker.ide.min.js:7
切换编译模式其他页面页出现了这样的问题

**Comment by xiaofuzi** [comment]
页面是否存在，如存在可查看下 my 页面模板是否有支付宝小程序不支持的语法？（附上 my.axml 截图）

**Comment by KDWangBoss** [comment]
问题解决了，是启用了component2编译的问题，谢谢
