### ISSUE TITLE
antmove怎么搬运第三方组件库呢？

### ISSUE THREAD

**Issue by liujiayii** [ant-move/Antmove#19]
现在想自己搬运vant组件库到支付宝，但是官网好像并没有提到怎么搬运组件库，求指教

**Comment by xiaofuzi** [comment]
https://github.com/ant-move/Vant-Aliapp 这里的说明能解决你的问题吗

**Comment by liujiayii** [comment]
看到那个仓库了，搬运的版本没有及时跟上vant啊，所以想自己搬一下

**Comment by liujiayii** [comment]
> https://github.com/ant-move/Vant-Aliapp 这里的说明能解决你的问题吗

已经用上了，就是vant那边最近更新了一些东西，咱这边能不能及时跟上= =
