### ISSUE TITLE
微信小程序转支付宝小程序 三方平台开发获取ext.json API不一致

### ISSUE THREAD

**Issue by connself** [ant-move/Antmove#34]
微信：
`wx.getExtConfig({
      success: res => {
        this.globalData.ext = res.extConfig;
      }
    })`
转换后：
`_my.getExtConfig({
      success: res => {
        this.globalData.ext = res.extConfig;
      }
    })`
正确的：
` this.globalData.ext=_my.getExtConfigSync()`

**Comment by xiaofuzi** [comment]
这里是指 `_my.getExtConfig` 异步版本的 api 不生效吗

**Comment by connself** [comment]
转换后支付宝小程序后 只有`_my.getExtConfigSync`这个API  没有`_my.getExtConfig`  导致获取不了ext.json信息
