### ISSUE TITLE
微信小程序转支付宝小程序编译

### ISSUE THREAD

**Issue by akbq2008** [ant-move/Antmove#40]
微信小程序转支付宝小程序编译中pages页面里面的json文件引用会多一个-comonent
原始的正确的：
![image](https://user-images.githubusercontent.com/20917699/88041654-4b209b00-cb7d-11ea-94cf-b167a9632dd8.png)
编译之后的：
![image](https://user-images.githubusercontent.com/20917699/88041539-24626480-cb7d-11ea-88fa-3f81d9bad089.png)

**Comment by xiaofuzi** [comment]
custome-share 是模拟的微信小程序 share 相关功能，引入路径可能有问题，我们这边处理尽快处理

**Comment by stanger-q** [comment]
引用的该组件是否作为页面使用了呢？如果方便的话可以+钉钉群21977588交流反馈
