### ISSUE TITLE
Cannot read property 'getRootNode' of undefined

### ISSUE THREAD

**Issue by shenjiuer** [ant-move/Antmove#42]
微信小程序转支付宝小程序
TypeError: Cannot read property 'getRootNode' of undefined
    at Object._opts.onReady (page.js:41)

**Comment by stanger-q** [comment]
可以尝试更新到最新版的Antmove进行转换

**Comment by stanger-q** [comment]
新版(1.1.6) 已修复此问题，感谢反馈，可加钉群(21977588)联系我们
