### ISSUE TITLE
转头条小程序 报错 TypeError: Cannot read property 'parent' of null

### ISSUE THREAD

**Issue by ttlb0814** [ant-move/Antmove#44]
通过 命令行方式转换的，，，通过 vscode上,输入 Antmove之后会出现Run antmove，点击后出现本项目的目录，确定后让我选择文件夹，请问这一步是什么意思？应该怎么操作，我新建文件夹点击确定后右下角提示我转换成功，但是找不到转换后的项目

**Comment by ttlb0814** [comment]
我通过vscode   ctrl + shift + p 的方式转换一个普通demo可以，但转换公司的项目文件没有反应新建一个文件夹，打开之后还是空的

**Comment by ttlb0814** [comment]
请问怎么回事呢

**Comment by stanger-q** [comment]
选择文件夹就是选择输出路径，感谢反馈，具体问题加钉群(21977588)联系我们！
