### ISSUE TITLE
Antmove转换的时候出现错误

### ISSUE THREAD

**Issue by wyying** [ant-move/Antmove#48]
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
![1604549512(1)](https://user-images.githubusercontent.com/15809193/98197038-aaee5680-1f60-11eb-9d8e-d9c071923de1.jpg)

**Comment by iamxiaobo** [comment]
是把微信小程序转到支付宝么？ 项目中是不是用到了wxParser这个库

**Comment by iamxiaobo** [comment]
大概率是wxParser库，该工具官方已停止维护，建议替换成微信官方的rich-text组件
