### ISSUE TITLE
转换之后的_antmove文件是做什么用的，里面的component文件中的utils下面的watchShakes.js文件是干什么用的

### ISSUE THREAD

**Issue by wyying** [ant-move/Antmove#51]
### 问题描述
_antmove文件下面的component文件中的utils下面的watchShakes.js文件是干什么用的，里面 let info = my.getStorage({
        key: '__antmove_loginfo'
    }).data是做什么用的，这个_antmove文件可以删除吗

**Comment by iamxiaobo** [comment]
这个文件是用于抹平跨小程序运行时差异的，不能删除；

如果遇到其它问题欢迎再反馈
