### ISSUE TITLE
Antmove将微信小程序转支付宝小程之后.a-image和.a-view样式是如何生成的，如何去掉

### ISSUE THREAD

**Issue by wyying** [ant-move/Antmove#55]
Antmove将微信小程序转支付宝小程之后.a-image和.a-view样式是如何生成的，如何去掉，转换之后发现自己写的样式有时候会被.a-image和.a-view的样式覆盖掉，请问这个样式是如何生成的，如何才能去掉

**Comment by iamxiaobo** [comment]
antmove添加的.a-xxx 开头的样式是实现将支付宝的默认样式改成偏微信风格

如果发现覆盖了你自己写的样式，可以通过提升css rule的优先级解决
