### ISSUE TITLE
vscode 装好了插件运行

### ISSUE THREAD

**Issue by silentzone** [ant-move/Antmove#57]
### 问题描述
描述下你遇到的问题

### 系统环境
- 出现问题的antmove版本：
- 没出现问题的antmove版本（如果有）：
- 操作系统：
- Node.js版本：
- 使用antmove命令行工具/vscode插件：
- 转换类型（微信转支付宝等等）：

### node命令执行时的报错
运行antmove命令时出现的报错信息

### IDE运行时调试窗口报错
在IDE或者真机上调试时出现的报错信息

**Comment by martianyi** [comment]
使用npm安装命令行版本，vscode插件最近没有更新
